import { PhonelinkOutlined, ToggleOn, AccountBalance, Business, Info, CloudUpload, 
  Security, AccountBox, CreditCard, Gavel, Description, LocalOffer, AccountCircle, 
  MoreHoriz } from '@mui/icons-material';
import { NavigationMetadata } from './types';

export const CONFIG_SECTIONS: Record<string, NavigationMetadata> = {
  'core-settings': {
    key: 'core-settings',
    groupId: 'core',
    sectionId: 'settings',
    label: 'Core Settings',
    icon: PhonelinkOutlined,
    category: 'System',
    description: 'Configure core platform settings and features',
  },
  'auth-security': {
    key: 'auth-security',
    groupId: 'auth',
    sectionId: 'security',
    label: 'Authentication & Security',
    icon: Security,
    category: 'Security',
    description: 'Manage authentication and security settings',
  },
  'accounts': {
    key: 'accounts',
    groupId: 'accounts',
    sectionId: 'main',
    label: 'Accounts',
    icon: AccountBox,
    category: 'Banking',
    description: 'Configure account-related settings',
  },
  'cards-payments': {
    key: 'cards-payments',
    groupId: 'cards',
    sectionId: 'payments',
    label: 'Cards & Payments',
    icon: CreditCard,
    category: 'Banking',
    description: 'Manage card and payment configurations',
  },
  'compliance-support': {
    key: 'compliance-support',
    groupId: 'compliance',
    sectionId: 'support',
    label: 'Compliance & Support',
    icon: Gavel,
    category: 'Operations',
    description: 'Configure compliance and support features',
  },
  'document-services': {
    key: 'document-services',
    groupId: 'documents',
    sectionId: 'services',
    label: 'Document Services',
    icon: Description,
    category: 'Services',
    description: 'Manage document processing and storage',
  },
  'loans-credit': {
    key: 'loans-credit',
    groupId: 'loans',
    sectionId: 'credit',
    label: 'Loans & Credit',
    icon: AccountBalance,
    category: 'Banking',
    description: 'Configure loan and credit settings',
  },
  'marketing-offers': {
    key: 'marketing-offers',
    groupId: 'marketing',
    sectionId: 'offers',
    label: 'Marketing & Offers',
    icon: LocalOffer,
    category: 'Marketing',
    description: 'Manage marketing campaigns and offers',
  },
  'user-services': {
    key: 'user-services',
    groupId: 'users',
    sectionId: 'services',
    label: 'User Services',
    icon: AccountCircle,
    category: 'Services',
    description: 'Configure user-related services',
  },
  'misc': {
    key: 'misc',
    groupId: 'misc',
    sectionId: 'main',
    label: 'Miscellaneous',
    icon: MoreHoriz,
    category: 'Other',
    description: 'Other configuration options',
  }
};
